# 다층 퍼셉트론 - XOR

In [1]:
import numpy as np

In [3]:
W1 = np.array([[-2,2],[-2,2]])
w11, w12 = W1[:,0], W1[:,1] 
w11, w12

(array([-2, -2]), array([2, 2]))

In [4]:
w2 = np.array([1,1])
b11, b12 = 3, -1
b2 = -1

In [5]:
# NAND Gate - n1
for x1, x2 in [(0,0), (0,1), (1,0), (1,1)]:
    sum = w11[0] * x1 + w11[1] * x2 + b11
    print(sum)

3
1
1
-1


In [6]:
# NAND Gate - n1
for x1, x2 in [(0,0), (0,1), (1,0), (1,1)]:
    sum = w11[0] * x1 + w11[1] * x2 + b11
    print(1 if sum > 0 else 0)              # sigmoid

1
1
1
0


In [7]:
# OR Gate - n2
for x1, x2 in [(0,0), (0,1), (1,0), (1,1)]:
    sum = w12[0] * x1 + w12[1] * x2 + b12
    print(sum)

-1
1
1
3


In [8]:
# OR Gate - n2
for x1, x2 in [(0,0), (0,1), (1,0), (1,1)]:
    sum = w12[0] * x1 + w12[1] * x2 + b12
    print(1 if sum > 0 else 0)

0
1
1
1


In [33]:
def perceptron(X, W, b):
    y = np.dot(W, X) + b                # y = WX + b
    return 1 if y > 0 else 0            # sigmoid 역할

In [31]:
# NAND 게이트
for x1, x2 in [(0,0), (0,1), (1,0), (1,1)]:
    x = np.array([x1, x2])
    print(perceptron(x, w11, b11))

1
1
1
0


In [25]:
# OR Gate
for x in [(0,0), (0,1), (1,0), (1,1)]:
    print(perceptron(np.array(x), w12, b12))

0
1
1
1


In [26]:
def nand_gate(x1, x2):
    return perceptron(np.array([x1,x2]), w11, b11)

def or_gate(x1, x2):
    return perceptron(np.array([x1,x2]), w12, b12)

def and_gate(x1, x2):
    return perceptron(np.array([x1,x2]), w2, b2)

In [27]:
for x in [(0,0), (0,1), (1,0), (1,1)]:
    ng = nand_gate(*x)
    og = or_gate(*x)
    xorg = and_gate(ng, og)
    print(f'입력값: {x}, 출력값: {xorg}')

입력값: (0, 0), 출력값: 0
입력값: (0, 1), 출력값: 1
입력값: (1, 0), 출력값: 1
입력값: (1, 1), 출력값: 0


In [28]:
def xor_gate(x1, x2):
    return and_gate(nand_gate(x1, x2), or_gate(x1, x2))

In [29]:
for x in [(0,0), (0,1), (1,0), (1,1)]:
    print(f'입력값: {x}, 출력값: {xor_gate(*x)}')

입력값: (0, 0), 출력값: 0
입력값: (0, 1), 출력값: 1
입력값: (1, 0), 출력값: 1
입력값: (1, 1), 출력값: 0


### Perceptron

In [34]:
W = np.array([2.3, 3.2, 5.8, -4.3])
X = np.array([0, 1, 1, 0])
bias = -3
perceptron(X, W, bias)

1

In [35]:
l = [1, 2, 3]
a = np.array(l)
type(l), type(a)

(list, numpy.ndarray)

In [36]:
l * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [37]:
a * 3

array([3, 6, 9])

In [39]:
a.reshape(1,-1)

array([[1, 2, 3]])

In [41]:
[l]

[[1, 2, 3]]

### 참고 사항
- 위치형 가변인수, 키워드형 가변인수를 사용할 때
- `*args`, `**kwargs` 와 같이 리스트(튜플) 언패킹, 딕셔너리 언패킹을 이용할 수 있음

In [18]:
z = [10, 20, 30]
print(z)

[10, 20, 30]


In [19]:
# list unpacking
print(*z)           # print(10, 20, 30)

10 20 30


In [23]:
# dictionary unpacking
d = {'sep':', ', 'end':'#######\n'}
print(d)

{'sep': ', ', 'end': '#######\n'}


In [24]:
print(1, 2, **d)            # print(1, 2, sep=', ', end='#######\n')

1, 2#######
