In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
a.sum(axis=0)

array([24, 28, 32, 36])

In [4]:
a.sum(axis=1)

array([ 6, 22, 38, 54])

In [5]:
df = pd.DataFrame(a, columns=list('ABCD'), index=list('wxyz'))
df

A   B   C   D
w   0   1   2   3
x   4   5   6   7
y   8   9  10  11
z  12  13  14  15

In [6]:
df['sum'] = df.sum(axis=1)
df

A   B   C   D  sum
w   0   1   2   3    6
x   4   5   6   7   22
y   8   9  10  11   38
z  12  13  14  15   54

In [8]:
df.drop(['x'], inplace=True)
df

A   B   C   D  sum
w   0   1   2   3    6
y   8   9  10  11   38
z  12  13  14  15   54

In [9]:
df.drop(columns=['sum'], inplace=True)
df

A   B   C   D
w   0   1   2   3
y   8   9  10  11
z  12  13  14  15